In [2]:
import numpy as np
import pandas as pd

In [3]:
df=pd.read_csv('state_wise_daily.csv')

In [4]:
df.head(15)

,Date,Date_YMD,Status,Total,Hospitalized,Recovered,Deceased,Mask,Sanitizer,Oxygen,...,RJ,SK,TN,TG,TR,UP,UT,WB,UN,State
0,14-Mar-20,14-03-2020,Confirmed,81,12,120,0,10,60,48,...,3,0,1,1,0,12,0,0,0,Maharashtra
1,14-Mar-20,14-03-2020,Recovered,9,25,5,2,20,1,38,...,1,0,0,0,0,4,0,0,0,Maharashtra
2,14-Mar-20,14-03-2020,Deceased,2,85,10,4,30,0,0,...,0,0,0,0,0,0,0,0,0,Maharashtra
3,15-Mar-20,15-03-2020,Confirmed,27,89,15,0,40,41,57,...,1,0,0,2,0,1,0,0,0,Maharashtra
4,15-Mar-20,15-03-2020,Recovered,4,10,5,21,50,4,55,...,2,0,0,1,0,0,0,0,0,Maharashtra
5,15-Mar-20,15-03-2020,Deceased,0,15,8,12,60,0,0,...,0,0,0,0,0,0,0,0,0,Maharashtra
6,16-Mar-20,16-03-2020,Confirmed,15,1,14,7,70,28,55,...,0,0,0,1,0,0,1,0,0,Maharashtra
7,16-Mar-20,16-03-2020,Recovered,1,0,56,4,80,11,131,...,0,0,1,0,0,0,0,0,0,Maharashtra
8,16-Mar-20,16-03-2020,Deceased,0,11,84,3,90,0,0,...,0,0,0,0,0,0,0,0,0,Maharashtra
9,17-Mar-20,17-03-2020,Confirmed,11,1,12,2,1,37,52,...,0,0,0,1,0,2,0,1,0,Maharashtra
10,17-Mar-20,17-03-2020,Recovered,1,1,156,7,6,0,89,...,0,0,0,0,0,1,0,0,0,Maharashtra
11,17-Mar-20,17-03-2020,Deceased,1,37,214,4,0,0,0,...,0,0,0,0,0,0,0,0,0,Maharashtra
12,18-Mar-20,18-03-2020,Confirmed,37,25,17,11,0,27,30,...,3,0,1,8,0,2,1,0,0,Maharashtra
13,18-Mar-20,18-03-2020,Recovered,0,29,85,14,13,11,95,...,0,0,0,0,0,0,0,0,0,Maharashtra
14,18-Mar-20,18-03-2020,Deceased,0,27,96,15,0,0,1,...,0,0,0,0,0,0,0,0,0,Maharashtra

In [5]:
total= df['Status'].value_counts().sum()

In [12]:
active= df[df['Status']=='Confirmed'].loc[:,["Total"]].sum()
active

Total    34284758
dtype: int64

In [7]:
recovered = df[df['Status']=='Recovered'].shape[0]

In [8]:
death= df[df['Status']=='Recovered'].shape[0]